<?php

namespace CVOBundle\Repository;
use CVOBundle\Entity\Address;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Mapping;

/**
 * AddressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AddressRepository extends \Doctrine\ORM\EntityRepository
{
    public function __construct(EntityManagerInterface $em)
    {
        parent::__construct($em, new Mapping\ClassMetadata(Address::class));
    }

    public function save(Address $address)
    {
        $this->_em->persist($address);
        $this->_em->flush();
    }

    public function edit(Address $address)
    {
        $this->_em->merge($address);
        $this->_em->flush();
    }

    public function delete(Address $address)
    {
        $this->_em->remove($address);
        $this->_em->flush();
    }
}
