<?php

namespace CVOBundle\Repository;
use CVOBundle\Entity\Customer;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Mapping;

/**
 * CustomerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerRepository extends \Doctrine\ORM\EntityRepository
{
    public function __construct(EntityManagerInterface $em)
    {
        parent::__construct($em, new Mapping\ClassMetadata(Customer::class));
    }

    public function save(Customer $customer)
    {
        $this->_em->persist($customer);
        $this->_em->flush();
    }

    public function edit(Customer $customer)
    {
        $this->_em->merge($customer);
        $this->_em->flush();
    }

    public function delete(Customer $customer)
    {
        $this->_em->remove($customer);
        $this->_em->flush();
    }
}
