<?php

namespace CVOBundle\Repository;
use CVOBundle\Entity\Visit;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Mapping;
use Symfony\Component\Validator\Constraints\Date;

/**
 * VisitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisitRepository extends \Doctrine\ORM\EntityRepository
{
    public function __construct(EntityManagerInterface $em)
    {
        parent::__construct($em, new Mapping\ClassMetadata(Visit::class));
    }

    public function save(Visit $visit)
    {
        $this->_em->persist($visit);
        $this->_em->flush();
    }

    public function findForthcoming()
    {
        $query = $this->_em->createQuery(
            "SELECT v
                FROM CVOBundle:Visit v
                WHERE v.date >= :today"
        );

        $query->setParameter('today', new \DateTime());

        return $query->getResult();
    }
}
