<?php

namespace CVOBundle\Repository;
use CVOBundle\Entity\Visit;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Mapping;

/**
 * VisitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisitRepository extends \Doctrine\ORM\EntityRepository
{
    public function __construct(EntityManagerInterface $em)
    {
        parent::__construct($em, new Mapping\ClassMetadata(Visit::class));
    }

    public function save(Visit $visit)
    {
        $this->_em->persist($visit);
        $this->_em->flush();
    }

    public function edit(Visit $visit)
    {
        $this->_em->merge($visit);
        $this->_em->flush();
    }

    public function delete(Visit $visit)
    {
        $this->_em->remove($visit);
        $this->_em->flush();
    }

    public function findForthcoming()
    {
        $query = $this->_em->createQuery(
            "SELECT v
                FROM CVOBundle:Visit v
                WHERE v.date >= :today
                AND v.isFinished = false
                ORDER BY v.date"
        );

        $query->setParameter('today', new \DateTime());

        return $query->getResult();
    }

    public function findForthcomingByUser($userId)
    {
        return $this->createQueryBuilder('v')
            ->where(':user_id MEMBER OF v.users AND v.isFinished = false')
            ->setParameter('user_id', $userId)
            ->orderBy('v.date')
            ->getQuery()
            ->getResult();
    }


}
